const form = document.getElementById("analyze-form");
const urlInput = document.getElementById("article-url");
const submitBtn = document.getElementById("submit-btn");
const debugModeEl = document.getElementById("debug-mode");

const statusEl = document.getElementById("status");
const activityEl = document.getElementById("activity");
const activityTextEl = document.getElementById("activity-text");
const progressFillEl = document.getElementById("progress-fill");
const resultsEl = document.getElementById("results");
const debugPanelEl = document.getElementById("debug-panel");
const debugLineEl = document.getElementById("debug-line");
const debugOutputEl = document.getElementById("debug-output");

const articleTitleEl = document.getElementById("article-title");
const articleLinkEl = document.getElementById("article-link");
const authorProfileEl = document.getElementById("author-profile");
const backgroundChecksEl = document.getElementById("background-checks");
const motivationsEl = document.getElementById("motivations");
const caveatsEl = document.getElementById("caveats");

let progressInterval = null;
let activityStartedAt = 0;

form.addEventListener("submit", async (event) => {
  event.preventDefault();

  const url = urlInput.value.trim();
  if (!url) return;

  if (!isLikelyHttpUrl(url)) {
    setStatus("Please provide a valid http(s) URL.", "error");
    return;
  }

  const debugEnabled = Boolean(debugModeEl.checked);

  setLoading(true);
  hideResults();
  clearDebug();
  startActivity("Submitting analysis request");
  setStatus("Analysis started. This can take up to a minute.", "info");

  try {
    setActivityStage("Waiting for server to fetch and parse article");
    const response = await fetch("/api/analyze", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ url, debug: debugEnabled })
    });

    setActivityStage("Waiting for AI provider response (this can be the slowest step)");
    const payload = await parseApiResponse(response);
    if (!response.ok) {
      throw new ApiError(payload.error || "Analysis failed.", payload, response.status);
    }

    setActivityStage("Building caveat report");
    renderResults(payload);
    if (debugEnabled && payload.debug) {
      renderDebug(payload.debug);
    }

    setStatus("Analysis complete.", "info");
  } catch (error) {
    const message = normalizeClientError(error);
    setStatus(message, "error");

    if (error instanceof ApiError && error.payload?.debug) {
      renderDebug(error.payload.debug);
    }
  } finally {
    stopActivity();
    setLoading(false);
  }
});

function renderResults(payload) {
  const { article, analysis } = payload;

  articleTitleEl.textContent = article.title || "Unknown";
  articleLinkEl.textContent = article.url;
  articleLinkEl.href = article.url;

  authorProfileEl.textContent =
    analysis.author_profile || "No profile generated by the model.";
  renderBackgroundChecks(analysis.background_checks || {});

  motivationsEl.innerHTML = "";
  const motivations = analysis.motivations || [];
  if (motivations.length === 0) {
    motivationsEl.innerHTML = "<li>No explicit motivations found.</li>";
  } else {
    for (const item of motivations) {
      const li = document.createElement("li");
      const strength = normalizeStrength(item.evidence_strength);
      const hint = item.evidence_hint || "No specific basis provided.";
      li.innerHTML = `<strong>${escapeHtml(item.factor || "Unknown factor")}</strong>: ${escapeHtml(item.impact || "No details.")}<br><em>Why this estimate:</em> ${escapeHtml(hint)}<br><em>Evidence strength:</em> <span class="tag ${strength}">${escapeHtml(strength)}</span>`;
      motivationsEl.appendChild(li);
    }
  }

  caveatsEl.innerHTML = "";
  const checks = analysis.key_claim_checks || [];
  if (checks.length === 0) {
    caveatsEl.innerHTML = "<p>No specific sentence caveats returned.</p>";
  } else {
    for (const check of checks) {
      const wrapper = document.createElement("div");
      wrapper.className = "caveat";

      const confidence = (check.confidence || "unknown").toLowerCase();
      const safeConfidence = ["high", "medium", "low"].includes(confidence)
        ? confidence
        : "low";

      wrapper.innerHTML = `
        <p><strong>Claim:</strong> ${escapeHtml(check.claim_sentence || "-")}</p>
        <p><strong>Possible motivation link:</strong> ${escapeHtml(check.potential_motivation_link || "-")}</p>
        <p><strong>Caveat:</strong> ${escapeHtml(check.caveat || "-")}</p>
        <p><strong>Confidence:</strong><span class="tag ${safeConfidence}">${escapeHtml(safeConfidence)}</span></p>
      `;

      caveatsEl.appendChild(wrapper);
    }
  }

  resultsEl.classList.remove("hidden");
}

function setStatus(message, mode) {
  statusEl.textContent = message;
  statusEl.classList.remove("hidden", "error", "info");
  statusEl.classList.add(mode || "info");
}

function hideResults() {
  resultsEl.classList.add("hidden");
}

function setLoading(isLoading) {
  submitBtn.disabled = isLoading;
  submitBtn.textContent = isLoading ? "Analyzing..." : "Analyze";
}

function startActivity(initialLabel = "Starting analysis") {
  clearInterval(progressInterval);
  activityEl.classList.remove("hidden");
  activityStartedAt = Date.now();
  setActivityStage(initialLabel);
  progressFillEl.style.width = "20%";

  progressInterval = setInterval(() => {
    const elapsed = Math.floor((Date.now() - activityStartedAt) / 1000);
    const baseText = activityTextEl.dataset.baseText || "Running analysis";
    activityTextEl.textContent = `${baseText} (${elapsed}s)`;
  }, 500);
}

function stopActivity() {
  clearInterval(progressInterval);
  progressInterval = null;
  progressFillEl.style.width = "100%";
  setTimeout(() => {
    activityEl.classList.add("hidden");
    progressFillEl.style.width = "0%";
  }, 500);
}

function setActivityStage(label) {
  const elapsed = Math.floor((Date.now() - activityStartedAt) / 1000);
  activityTextEl.dataset.baseText = label;
  activityTextEl.textContent = `${label} (${elapsed}s)`;

  const lower = label.toLowerCase();
  if (lower.includes("submitting")) {
    progressFillEl.style.width = "20%";
    return;
  }
  if (lower.includes("fetch")) {
    progressFillEl.style.width = "35%";
    return;
  }
  if (lower.includes("waiting for ai provider")) {
    progressFillEl.style.width = "70%";
    return;
  }
  if (lower.includes("building caveat")) {
    progressFillEl.style.width = "90%";
  }
}

async function parseApiResponse(response) {
  const rawText = await response.text();
  if (!rawText) return {};

  try {
    return JSON.parse(rawText);
  } catch {
    if (!response.ok) {
      const excerpt = rawText.replace(/\s+/g, " ").slice(0, 220);
      return {
        error: `Server returned non-JSON error (HTTP ${response.status}). ${excerpt}`
      };
    }

    throw new Error("Server returned invalid JSON response.");
  }
}

function renderDebug(debugPayload) {
  const authorSource = debugPayload?.extra?.author_source || "unknown";
  const extractedAuthor = debugPayload?.extra?.extracted_author || "Unknown author";
  const extractedSource = debugPayload?.extra?.extracted_author_source || "unknown";
  const analysisSubject = debugPayload?.extra?.analysis_subject || "Unknown author";
  debugLineEl.textContent =
    `Analysis subject: ${analysisSubject} (source: ${authorSource}) | ` +
    `Extracted author: ${extractedAuthor} (source: ${extractedSource})`;
  debugOutputEl.textContent = JSON.stringify(debugPayload, null, 2);
  debugPanelEl.classList.remove("hidden");
}

function clearDebug() {
  debugLineEl.textContent = "";
  debugOutputEl.textContent = "";
  debugPanelEl.classList.add("hidden");
}

function isLikelyHttpUrl(input) {
  try {
    const parsed = new URL(input);
    return parsed.protocol === "http:" || parsed.protocol === "https:";
  } catch {
    return false;
  }
}

function normalizeStrength(value) {
  const normalized = String(value || "").toLowerCase();
  return ["high", "medium", "low"].includes(normalized) ? normalized : "low";
}

function renderBackgroundChecks(checks) {
  const affiliations = checks.author_affiliations || [];
  const residence = checks.author_country_of_residence || {};
  const leadEditor = checks.publisher_lead_editor_or_redactor || {};

  const affiliationsHtml =
    affiliations.length === 0
      ? "<li>No clear affiliations found.</li>"
      : affiliations
          .map((item) => {
            const confidence = normalizeStrength(item.confidence);
            return `<li><strong>${escapeHtml(item.name || "Unknown")}</strong> (${escapeHtml(item.relationship || "unknown")})<br><em>Evidence:</em> ${escapeHtml(item.evidence_hint || "No details.")}<br><em>Confidence:</em> <span class=\"tag ${confidence}\">${escapeHtml(confidence)}</span></li>`;
          })
          .join("");

  const countryConfidence = normalizeStrength(residence.confidence);
  const editorConfidence = normalizeStrength(leadEditor.confidence);

  backgroundChecksEl.innerHTML = `
    <p><strong>Author Country of Residence:</strong> ${escapeHtml(residence.country || "Unknown")}</p>
    <p><em>Evidence:</em> ${escapeHtml(residence.evidence_hint || "No details.")} <span class="tag ${countryConfidence}">${escapeHtml(countryConfidence)}</span></p>
    <p><strong>Publisher Lead Editor / Redactor:</strong> ${escapeHtml(leadEditor.name || "Unknown")} (${escapeHtml(leadEditor.role || "unknown")})</p>
    <p><em>Evidence:</em> ${escapeHtml(leadEditor.evidence_hint || "No details.")} <span class="tag ${editorConfidence}">${escapeHtml(editorConfidence)}</span></p>
    <p><strong>Affiliations</strong></p>
    <ul>${affiliationsHtml}</ul>
  `;
}

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

class ApiError extends Error {
  constructor(message, payload, status) {
    super(message);
    this.name = "ApiError";
    this.payload = payload;
    this.status = status;
  }
}

function normalizeClientError(error) {
  const fallback = "Unable to analyze this article.";
  if (!(error instanceof Error)) return fallback;

  const msg = String(error.message || "");
  const lower = msg.toLowerCase();

  if (lower.includes("failed to fetch") || lower.includes("load failed")) {
    return "Could not reach /api/analyze (network load failed). Check that the local dev server is running and retry.";
  }

  return msg || fallback;
}
