const form = document.getElementById("analyze-form");
const urlInput = document.getElementById("article-url");
const submitBtn = document.getElementById("submit-btn");
const debugModeEl = document.getElementById("debug-mode");
const langButtons = [...document.querySelectorAll("[data-lang]")];

const statusEl = document.getElementById("status");
const activityEl = document.getElementById("activity");
const activityTextEl = document.getElementById("activity-text");
const progressFillEl = document.getElementById("progress-fill");
const resultsEl = document.getElementById("results");
const debugPanelEl = document.getElementById("debug-panel");
const debugLineEl = document.getElementById("debug-line");
const debugOutputEl = document.getElementById("debug-output");

const articleTitleEl = document.getElementById("article-title");
const articleLinkEl = document.getElementById("article-link");
const authorProfileEl = document.getElementById("author-profile");
const backgroundChecksEl = document.getElementById("background-checks");
const motivationsEl = document.getElementById("motivations");
const caveatsEl = document.getElementById("caveats");

const i18n = {
  eyebrow: document.getElementById("eyebrow"),
  subtitle: document.getElementById("subtitle"),
  quoteText: document.getElementById("quote-text"),
  quoteSource: document.getElementById("quote-source"),
  labelArticleUrl: document.getElementById("label-article-url"),
  labelDebugToggle: document.getElementById("label-debug-toggle"),
  hint: document.getElementById("hint"),
  headingArticle: document.getElementById("heading-article"),
  headingAuthorProfile: document.getElementById("heading-author-profile"),
  headingBackgroundChecks: document.getElementById("heading-background-checks"),
  headingMotivations: document.getElementById("heading-motivations"),
  headingCaveats: document.getElementById("heading-caveats"),
  headingDebug: document.getElementById("heading-debug"),
  labelArticleTitle: document.getElementById("label-article-title"),
  labelArticleSource: document.getElementById("label-article-source"),
  pageTitle: document.getElementById("page-title")
};

const STRINGS = {
  en: {
    eyebrow: "AI-assisted source skepticism",
    subtitle:
      "Paste an article URL. Get possible author motivations, affiliations, and pressure points.",
    quoteText:
      "If you're not amazed by AI, you don't really understand it. If you're not afraid of AI, you don't really understand it.",
    quoteSource: "Mustafa Suleyman, CEO Microsoft AI & Co-Founder Deepmind",
    labelArticleUrl: "Article URL",
    placeholderUrl: "https://example.com/article",
    analyze: "Analyze",
    analyzing: "Analyzing...",
    debugToggle: "Enable developer debug details",
    hint:
      "This is a first-pass AI assessment and may include uncertainty. Always verify critical claims manually.",
    headingArticle: "Article",
    headingAuthorProfile: "Author Profile",
    headingBackgroundChecks: "Publisher Profile",
    headingMotivations: "Potential Motivations / Influences",
    headingCaveats: "Claim Caveats",
    headingDebug: "Debug Details",
    labelArticleTitle: "Title:",
    labelArticleSource: "Source URL:",
    pageTitle: "Unhide the hidden agenda",
    statusInvalidUrl: "Please provide a valid http(s) URL.",
    statusStarted: "Analysis started. This can take up to a minute.",
    statusComplete: "Analysis complete.",
    activityStarting: "Submitting analysis request",
    activityFetch: "Waiting for server to fetch and parse article",
    activityModel: "Waiting for AI provider response (this can be the slowest step)",
    activityBuild: "Building caveat report",
    unknown: "Unknown",
    noProfile: "No profile generated by the model.",
    noMotivations: "No explicit motivations found.",
    noCaveats: "No specific sentence caveats returned.",
    claimLabel: "Claim",
    motivationLabel: "Possible motivation link",
    caveatLabel: "Caveat",
    authorResidence: "Author Country of Residence",
    leadEditor: "Publisher Lead Editor / Redactor",
    affiliations: "Affiliations",
    noAffiliations: "No clear affiliations found.",
    whyEstimate: "Why this estimate",
    publisherProfile: "Publisher Profile",
    publisherFunding: "Publisher Funding / Ownership Signals",
    noFunding: "No clear funding or ownership signals found.",
    noEvidence: "No specific basis provided.",
    noDetails: "No details.",
    source: "Sources:",
    unknownRelationship: "unknown",
    errorApiUnreachable:
      "Could not reach /api/analyze (network load failed). Check that the local dev server is running and retry.",
    errorGeneric: "Unable to analyze this article."
  },
  de: {
    eyebrow: "KI-gestützte Quellenkritik",
    subtitle:
      "Füge eine Artikel-URL ein. Erhalte mögliche Motive, Zugehörigkeiten und Druckpunkte des Autors.",
    quoteText:
      "Wenn dich KI nicht staunen lässt, verstehst du sie nicht wirklich. Wenn dich KI nicht beunruhigt, verstehst du sie nicht wirklich.",
    quoteSource: "Mustafa Suleyman, CEO Microsoft AI & Co-Founder DeepMind",
    labelArticleUrl: "Artikel-URL",
    placeholderUrl: "https://beispiel.de/artikel",
    analyze: "Analysieren",
    analyzing: "Analyse läuft...",
    debugToggle: "Entwickler-Debugdetails anzeigen",
    hint:
      "Dies ist eine erste KI-Einschätzung und kann Unsicherheiten enthalten. Prüfe kritische Aussagen immer manuell.",
    headingArticle: "Artikel",
    headingAuthorProfile: "Autor-Profil",
    headingBackgroundChecks: "Publisher-Profil",
    headingMotivations: "Mögliche Motive / Einflüsse",
    headingCaveats: "Behauptungs-Hinweise",
    headingDebug: "Debug-Details",
    labelArticleTitle: "Titel:",
    labelArticleSource: "Quelle (URL):",
    pageTitle: "Enthülle das verborgene Motiv",
    statusInvalidUrl: "Bitte eine gültige http(s)-URL angeben.",
    statusStarted: "Analyse gestartet. Das kann bis zu einer Minute dauern.",
    statusComplete: "Analyse abgeschlossen.",
    activityStarting: "Analyseanfrage wird gesendet",
    activityFetch: "Server lädt und verarbeitet den Artikel",
    activityModel: "Warte auf die KI-Antwort (dies ist oft der langsamste Schritt)",
    activityBuild: "Bericht wird zusammengestellt",
    unknown: "Unbekannt",
    noProfile: "Kein Profil vom Modell erzeugt.",
    noMotivations: "Keine klaren Motive gefunden.",
    noCaveats: "Keine konkreten Satz-Hinweise zurückgegeben.",
    claimLabel: "Aussage",
    motivationLabel: "Möglicher Motiv-Zusammenhang",
    caveatLabel: "Hinweis",
    authorResidence: "Land des Wohnsitzes der Autorin / des Autors",
    leadEditor: "Leitende Redaktion / Redaktionsleitung",
    affiliations: "Zugehörigkeiten",
    noAffiliations: "Keine klaren Zugehörigkeiten gefunden.",
    whyEstimate: "Warum diese Einschätzung",
    publisherProfile: "Publisher-Profil",
    publisherFunding: "Finanzierung / Eigentümer-Signale",
    noFunding: "Keine klaren Hinweise auf Finanzierung oder Eigentümerschaft gefunden.",
    noEvidence: "Keine konkrete Grundlage angegeben.",
    noDetails: "Keine Details.",
    source: "Quellen:",
    unknownRelationship: "unbekannt",
    errorApiUnreachable:
      "/api/analyze ist nicht erreichbar (Netzwerkfehler). Prüfe, ob der lokale Dev-Server läuft, und versuche es erneut.",
    errorGeneric: "Artikel konnte nicht analysiert werden."
  }
};

let progressInterval = null;
let activityStartedAt = 0;
let currentLang = resolveInitialLanguage();
let runtimeModel = "gpt-4.1-mini";

form.addEventListener("submit", async (event) => {
  event.preventDefault();

  const url = urlInput.value.trim();
  if (!url) return;

  if (!isLikelyHttpUrl(url)) {
    setStatus(t("statusInvalidUrl"), "error");
    return;
  }

  const debugEnabled = Boolean(debugModeEl.checked);

  setLoading(true);
  hideResults();
  clearDebug();
  startActivity(t("activityStarting"));
  setStatus(t("statusStarted"), "info");

  try {
    setActivityStage(t("activityFetch"));
    const response = await fetch("/api/analyze", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ url, debug: debugEnabled, lang: currentLang })
    });

    setActivityStage(getActivityModelLabel());
    const payload = await parseApiResponse(response);
    if (!response.ok) {
      throw new ApiError(payload.error || "Analysis failed.", payload, response.status);
    }

    setActivityStage(t("activityBuild"));
    renderResults(payload);
    if (debugEnabled && payload.debug) {
      renderDebug(payload.debug);
    }

    setStatus(t("statusComplete"), "info");
  } catch (error) {
    const message = normalizeClientError(error);
    setStatus(message, "error");

    if (error instanceof ApiError && error.payload?.debug) {
      renderDebug(error.payload.debug);
    }
  } finally {
    stopActivity();
    setLoading(false);
  }
});

function renderResults(payload) {
  const { article, analysis } = payload;

  articleTitleEl.textContent = article.title || t("unknown");
  articleLinkEl.textContent = article.url;
  articleLinkEl.href = article.url;

  const authorProfileLinks = renderSourceLinks(analysis.author_profile_source_urls);
  authorProfileEl.innerHTML = `${escapeHtml(analysis.author_profile || t("noProfile"))}${authorProfileLinks}`;
  renderBackgroundChecks(
    analysis.background_checks || {},
    analysis.publisher_profile || "",
    analysis.publisher_profile_source_urls || []
  );

  motivationsEl.innerHTML = "";
  const motivations = analysis.motivations || [];
  if (motivations.length === 0) {
    motivationsEl.innerHTML = `<li>${t("noMotivations")}</li>`;
  } else {
    for (const item of motivations) {
      const li = document.createElement("li");
      const hint = item.evidence_hint || t("noEvidence");
      li.innerHTML = `<strong>${escapeHtml(item.factor || t("unknown"))}</strong>: ${escapeHtml(item.impact || t("noDetails"))}<br>${escapeHtml(hint)}${renderSourceLinks(item.source_urls)}`;
      motivationsEl.appendChild(li);
    }
  }

  caveatsEl.innerHTML = "";
  const checks = analysis.key_claim_checks || [];
  if (checks.length === 0) {
    caveatsEl.innerHTML = `<p>${t("noCaveats")}</p>`;
  } else {
    for (const check of checks) {
      const wrapper = document.createElement("div");
      wrapper.className = "caveat";

      wrapper.innerHTML = `
        <p><strong>${escapeHtml(t("claimLabel"))}:</strong> ${escapeHtml(check.claim_sentence || "-")}</p>
        <p><strong>${escapeHtml(t("motivationLabel"))}:</strong> ${escapeHtml(check.potential_motivation_link || "-")}</p>
        <p><strong>${escapeHtml(t("caveatLabel"))}:</strong> ${escapeHtml(check.caveat || "-")}</p>
        <p>${renderSourceLinks(check.source_urls, true)}</p>
      `;

      caveatsEl.appendChild(wrapper);
    }
  }

  resultsEl.classList.remove("hidden");
}

function setStatus(message, mode) {
  statusEl.textContent = message;
  statusEl.classList.remove("hidden", "error", "info");
  statusEl.classList.add(mode || "info");
}

function hideResults() {
  resultsEl.classList.add("hidden");
}

function setLoading(isLoading) {
  submitBtn.disabled = isLoading;
  submitBtn.textContent = isLoading ? t("analyzing") : t("analyze");
}

function startActivity(initialLabel = "Starting analysis") {
  clearInterval(progressInterval);
  activityEl.classList.remove("hidden");
  activityStartedAt = Date.now();
  setActivityStage(initialLabel);
  progressFillEl.style.width = "20%";

  progressInterval = setInterval(() => {
    const elapsed = Math.floor((Date.now() - activityStartedAt) / 1000);
    const baseText = activityTextEl.dataset.baseText || "Running analysis";
    activityTextEl.textContent = `${baseText} (${elapsed}s)`;
  }, 500);
}

function stopActivity() {
  clearInterval(progressInterval);
  progressInterval = null;
  progressFillEl.style.width = "100%";
  setTimeout(() => {
    activityEl.classList.add("hidden");
    progressFillEl.style.width = "0%";
  }, 500);
}

function setActivityStage(label) {
  const elapsed = Math.floor((Date.now() - activityStartedAt) / 1000);
  activityTextEl.dataset.baseText = label;
  activityTextEl.textContent = `${label} (${elapsed}s)`;

  const lower = label.toLowerCase();
  if (lower.includes("submitting")) {
    progressFillEl.style.width = "20%";
    return;
  }
  if (lower.includes("fetch")) {
    progressFillEl.style.width = "35%";
    return;
  }
  if (lower.includes("waiting for ai provider")) {
    progressFillEl.style.width = "70%";
    return;
  }
  if (lower.includes("building caveat")) {
    progressFillEl.style.width = "90%";
  }
}

async function parseApiResponse(response) {
  const rawText = await response.text();
  if (!rawText) return {};

  try {
    return JSON.parse(rawText);
  } catch {
    if (!response.ok) {
      const excerpt = rawText.replace(/\s+/g, " ").slice(0, 220);
      return {
        error: `Server returned non-JSON error (HTTP ${response.status}). ${excerpt}`
      };
    }

    throw new Error("Server returned invalid JSON response.");
  }
}

function renderDebug(debugPayload) {
  const authorSource = debugPayload?.extra?.author_source || "unknown";
  const extractedAuthor = debugPayload?.extra?.extracted_author || "Unknown author";
  const extractedSource = debugPayload?.extra?.extracted_author_source || "unknown";
  const analysisSubject = debugPayload?.extra?.analysis_subject || "Unknown author";
  debugLineEl.textContent =
    `Analysis subject: ${analysisSubject} (source: ${authorSource}) | ` +
    `Extracted author: ${extractedAuthor} (source: ${extractedSource})`;
  debugOutputEl.textContent = JSON.stringify(debugPayload, null, 2);
  debugPanelEl.classList.remove("hidden");
}

function clearDebug() {
  debugLineEl.textContent = "";
  debugOutputEl.textContent = "";
  debugPanelEl.classList.add("hidden");
}

function isLikelyHttpUrl(input) {
  try {
    const parsed = new URL(input);
    return parsed.protocol === "http:" || parsed.protocol === "https:";
  } catch {
    return false;
  }
}

function renderBackgroundChecks(checks, publisherProfile, publisherProfileSourceUrls) {
  const affiliations = checks.author_affiliations || [];
  const residence = checks.author_country_of_residence || {};
  const leadEditor = checks.publisher_lead_editor_or_redactor || {};
  const fundingSources = checks.publisher_funding_sources || [];

  const affiliationsHtml =
    affiliations.length === 0
      ? `<li>${t("noAffiliations")}</li>`
      : affiliations
          .map((item) => {
            return `<li><strong>${escapeHtml(item.name || t("unknown"))}</strong> (${escapeHtml(item.relationship || t("unknownRelationship"))})<br>${escapeHtml(item.evidence_hint || t("noDetails"))}${renderSourceLinks(item.source_urls)}</li>`;
          })
          .join("");

  const fundingHtml =
    fundingSources.length === 0
      ? `<li>${t("noFunding")}</li>`
      : fundingSources
          .map((item) => {
            return `<li><strong>${escapeHtml(item.name || t("unknown"))}</strong><br>${escapeHtml(item.evidence_hint || t("noDetails"))}${renderSourceLinks(item.source_urls)}</li>`;
          })
          .join("");

  backgroundChecksEl.innerHTML = `
    ${publisherProfile ? `<p><strong>${escapeHtml(t("publisherProfile"))}:</strong> ${escapeHtml(publisherProfile)}${renderSourceLinks(publisherProfileSourceUrls)}</p>` : ""}
    <p><strong>${escapeHtml(t("authorResidence"))}:</strong> ${escapeHtml(residence.country || t("unknown"))}</p>
    <p>${escapeHtml(residence.evidence_hint || t("noDetails"))}${renderSourceLinks(residence.source_urls)}</p>
    <p><strong>${escapeHtml(t("leadEditor"))}:</strong> ${escapeHtml(leadEditor.name || t("unknown"))} (${escapeHtml(leadEditor.role || "unknown")})</p>
    <p>${escapeHtml(leadEditor.evidence_hint || t("noDetails"))}${renderSourceLinks(leadEditor.source_urls)}</p>
    <p><strong>${escapeHtml(t("affiliations"))}</strong></p>
    <ul>${affiliationsHtml}</ul>
    <p><strong>${escapeHtml(t("publisherFunding"))}</strong></p>
    <ul>${fundingHtml}</ul>
  `;
}

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function renderSourceLinks(urls, inline = false) {
  const safeUrls = normalizeSourceUrls(urls);
  if (safeUrls.length === 0) return "";
  const links = safeUrls
    .map((url) => {
      const safeUrl = escapeHtml(url);
      return `<a class="evidence-link" href="${safeUrl}" target="_blank" rel="noopener noreferrer" title="${safeUrl}">${escapeHtml(formatSourceLinkText(url))}</a>`;
    })
    .join(" ");
  const prefix = inline ? "" : "<br>";
  return `${prefix}<span class="source-list-label">${escapeHtml(t("source"))}</span> ${links}`;
}

function normalizeSourceUrls(value) {
  if (Array.isArray(value)) {
    return value.filter((item) => typeof item === "string" && item.trim());
  }
  if (typeof value === "string" && value.trim()) {
    return [value.trim()];
  }
  return [];
}

function formatSourceLinkText(url) {
  try {
    const parsed = new URL(url);
    const host = parsed.hostname.replace(/^www\./, "");
    const segments = parsed.pathname.split("/").filter(Boolean);
    const lastSegment = segments.at(-1) || "";
    const decodedSegment = decodeURIComponent(lastSegment)
      .replace(/[-_]+/g, " ")
      .replace(/\.[a-z0-9]+$/i, "")
      .trim();

    if (decodedSegment) {
      return `${host} - ${decodedSegment}`;
    }

    return host;
  } catch {
    return url;
  }
}

class ApiError extends Error {
  constructor(message, payload, status) {
    super(message);
    this.name = "ApiError";
    this.payload = payload;
    this.status = status;
  }
}

function normalizeClientError(error) {
  const fallback = t("errorGeneric");
  if (!(error instanceof Error)) return fallback;

  const msg = String(error.message || "");
  const lower = msg.toLowerCase();

  if (lower.includes("failed to fetch") || lower.includes("load failed")) {
    return t("errorApiUnreachable");
  }

  return msg || fallback;
}

function resolveInitialLanguage() {
  const stored = localStorage.getItem("lang");
  if (stored === "en" || stored === "de") return stored;
  const browser = navigator.language || "";
  return browser.toLowerCase().startsWith("de") ? "de" : "en";
}

function setLanguage(lang) {
  if (!STRINGS[lang]) return;
  currentLang = lang;
  localStorage.setItem("lang", lang);
  document.documentElement.lang = lang;
  applyLanguage();
}

function applyLanguage() {
  setText(i18n.eyebrow, t("eyebrow"));
  setText(i18n.subtitle, t("subtitle"));
  setText(i18n.quoteText, t("quoteText"));
  setText(i18n.quoteSource, t("quoteSource"));
  setText(i18n.labelArticleUrl, t("labelArticleUrl"));
  setText(i18n.labelDebugToggle, t("debugToggle"));
  setText(i18n.hint, t("hint"));
  setText(i18n.headingArticle, t("headingArticle"));
  setText(i18n.headingAuthorProfile, t("headingAuthorProfile"));
  setText(i18n.headingBackgroundChecks, t("headingBackgroundChecks"));
  setText(i18n.headingMotivations, t("headingMotivations"));
  setText(i18n.headingCaveats, t("headingCaveats"));
  setText(i18n.headingDebug, t("headingDebug"));
  setText(i18n.labelArticleTitle, t("labelArticleTitle"));
  setText(i18n.labelArticleSource, t("labelArticleSource"));
  const titleText = t("pageTitle");
  setText(i18n.pageTitle, titleText);
  document.title = titleText;
  const titleTag = document.querySelector("title");
  if (titleTag) titleTag.textContent = titleText;

  urlInput.placeholder = t("placeholderUrl");
  submitBtn.textContent = submitBtn.disabled ? t("analyzing") : t("analyze");

  for (const button of langButtons) {
    button.classList.toggle("active", button.dataset.lang === currentLang);
  }
}

function setText(el, value) {
  if (el) {
    el.textContent = value;
  }
}

function t(key) {
  return STRINGS[currentLang]?.[key] || STRINGS.en[key] || key;
}

function getActivityModelLabel() {
  return `${t("activityModel")} (${runtimeModel})`;
}

async function loadRuntimeConfig() {
  try {
    const response = await fetch("/api/runtime-config");
    if (!response.ok) return;
    const payload = await response.json();
    if (payload?.model) {
      runtimeModel = payload.model;
    }
  } catch {
    // Keep default model label when runtime config is unavailable.
  }
}

for (const button of langButtons) {
  button.addEventListener("click", () => {
    setLanguage(button.dataset.lang);
  });
}

setLanguage(currentLang);
loadRuntimeConfig();
